Updated post deployment check script

diff --git a/java-sample-application/kustomize-manifest/overlays/stage/script-config-map.yaml b/java-sample-application/kustomize-manifest/overlays/stage/script-config-map.yaml
--- a/java-sample-application/kustomize-manifest/overlays/stage/script-config-map.yaml
+++ b/java-sample-application/kustomize-manifest/overlays/stage/script-config-map.yaml
@@ -5,14 +5,21 @@ metadata:
 data:
   status_test.sh: |+
       #!/bin/bash
-      sleep 120
+      echo "Running post deployment checks...."
+      sleep 60
       productcatalog_status_code=$(curl http:/productcatalogue:8020/products -s -o /dev/null -w %{http_code})
       shopfront_status_code=$(curl http://shopfront:8010/ -s -o /dev/null -w %{http_code})
       if [ ${productcatalog_status_code} -eq 200 ] && [ ${shopfront_status_code} -eq 200 ]
       then
-      curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/shehbaz-pathan/Inception-argo-demo/actions/workflows/prod-deployment.yaml/dispatches -d '{"ref":"master"}' --http1.1
-      echo "Test successful, triggered prod workflow"
-      exit 0
+      curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/shehbaz-pathan/Inception-argo-demo/actions/workflows/prod-deployment.yaml/dispatches" -d '{"ref":"master"}'
+      if [ $? -eq 0 ]
+      then
+        echo "Test successful, triggered stage workflow"
+        exit 0
+      else
+        echo "Failed to triger stage workflow"
+        exit 1
+      fi
       else
       echo "Test failed"
       exit 1
