Update ci-productcatalogue.yaml

diff --git a/.github/workflows/ci-productcatalogue.yaml b/.github/workflows/ci-productcatalogue.yaml
--- a/.github/workflows/ci-productcatalogue.yaml
+++ b/.github/workflows/ci-productcatalogue.yaml
@@ -5,7 +5,7 @@ on:
       - master
       - 'feature/**'
     paths:
-      - java-sample-application/source-code/productcatalogue/**
+     - java-sample-application/source-code/productcatalogue/**
   pull_request:
     branches:
       - master
@@ -107,6 +107,23 @@ jobs:
 
     - name: Test
       run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
+    - name: Test Report
+      uses: phoenix-actions/test-reporting@v8
+      id: test-report 
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: JEST Tests            # Name of the check run which will be created
+        path: ${{ secrets.TEST_RESULT_PATH }}    # Path to test results
+        reporter: java-junit       # Format of test results
+        fail-on-error: 'false'
+    - name: Read output variables
+      run: |
+         echo "url is ${{ steps.test-report.outputs.runHtmlUrl }}"
+    - name: Publish Test Results for shopfront
+      uses: EnricoMi/publish-unit-test-result-action@v2
+      if: always()
+      with:
+        junit_files: "${{ secrets.TEST_RESULT_PATH }}"
 
     - name: Build and analyze
       env:
@@ -132,24 +149,21 @@ jobs:
     
     
     - name: Build Docker container
-      working-directory: ${{secrets.DOCKER_FILE_PATH_1 }}
+      working-directory: ${{secrets.DOCKER_FILE_PATH_2 }}
       run: |
-        docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME_1 }}:${{ github.sha }} .
+        docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME_2 }}:${{ github.sha }} .
     
-    - name: Run Trivy vulnerability scanner image catalog
+    - name: Run Trivy vulnerability scanner for shopfront
       uses: aquasecurity/trivy-action@master
       with:
-        image-ref: 'docker.io/${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME_1 }}:${{ github.sha }}'
+        image-ref: 'docker.io/${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME_2 }}:${{ github.sha }}'
         format: 'template'
 #        exit-code: '1'
         template: '@/contrib/sarif.tpl'
         output: 'trivy-results.sarif'
-      #  format: 'table'
-#        exit-code: '1'
         ignore-unfixed: true
         vuln-type: 'os,library'
         severity: 'CRITICAL,HIGH'
-
     - name: Upload trivy scan results to github security tab
       uses: github/codeql-action/upload-sarif@v2
       with:
@@ -157,8 +171,8 @@ jobs:
 
     - name: Docker push
       run: |
-        docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME_1 }}:${{ github.sha }}
-
+        docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME_2 }}:${{ github.sha }}
+    
     - name: release
       if: (github.ref == 'refs/heads/master')
       uses: actions/create-release@v1
@@ -167,7 +181,7 @@ jobs:
         draft: false
         prerelease: false
         release_name: ${{ steps.project.outputs.version }}.${{ steps.buildnumber.outputs.build_number }}
-        tag_name: "${{ github.ref }}-${{ secrets.IMAGE_NAME_1 }}-${{ steps.buildnumber.outputs.build_number }}"
+        tag_name: "${{ github.ref }}-${{ secrets.IMAGE_NAME_2 }}-${{ steps.buildnumber.outputs.build_number }}"
       env:
         GITHUB_TOKEN: ${{ github.token }}
 
@@ -175,25 +189,14 @@ jobs:
       uses: actions/checkout@v2
       with:
         ref: 'argocd'
-  call-workflow-in-local-repo:
-     uses: ./.github/workflows/docker-image-updater.yaml@master
-     with: 
-       destination-file: ./java-sample-application/kustomize-manifest/overlays/test/kustomization.yaml
-
-#  - name: Update Version for productcatalouge image
-  #    #if: steps.productcatalouge.outputs.any_changed == 'true'
-  #    run: |
-  #       version=$(cat ./java-sample-application/kustomize-manifest/overlays/test/kustomization.yaml | grep productcatalouge-image: | awk '{print $2}' | cut -d ':' -f 2 | rev | cut -c2- | rev)
-  #       echo "$version for test enviornment"
-  #       sed -i "s/$version/${{ github.sha }}/" ./java-sample-application/kustomize-manifest/overlays/test/kustomization.yaml
-  #       cat ./java-sample-application/kustomize-manifest/overlays/test/kustomization.yaml | grep productcatalouge-image: | awk '{print $2}' 
-
-
+  
+    - name: docker image updater 
+      uses: ./.github/workflows/docker-image-updater.yaml@master
+      with:
+          destination-file: ./java-sample-application/kustomize-manifest/overlays/test/kustomization.yaml
+  
     - name: Commit and push changes
       uses: devops-infra/action-commit-push@v0.3
       with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Image version updated
-    
-    
-          
